### PR TITLE
ENH: Update extension metadata

### PR DESCRIPTION
**Pull request by jcfr**
Consolidate extension metadata based on the corresponding s4ext file organized
in the ExtensionsIndex repository.

### CODE REVIEW

**Comment by jcfr** [comment]
@tokjun It would be great if this could be reviewed & integrated :pray: 

cc: @lassoan @pieper

**Comment by jcfr** [comment]
Please, could this be reviewed & merged :pray:

**Comment by jcfr** [comment]
Email sent on June 13th 2024 to @tokjun with @lassoan, @pieper and @che85 in cc:

```
Subject: Help to merge CurveMaker and ErodeDilateLabel pull requests

Hi Junichi,

When you have a chance, we would appreciate your help to merge the following pull requests:

  ENH: Update extension metadata
  https://github.com/tokjun/ErodeDilateLabel/pull/3

  ENH: Update extension metadata
  https://github.com/tokjun/CurveMaker/pull/17

along with these ones

  constant name changed in slicer core, see issue #10
  https://github.com/tokjun/CurveMaker/pull/11

  Feature added
  https://github.com/tokjun/CurveMaker/pull/9

Questions:

  To streamline maintenance, should we consider transferring any of these repositories to the Slicer organization ?
 
  Should we look into archiving them since similar functionalities may now be available in Slicer core ?

Thanks
J-Christophe
```

**Comment by tokjun** [comment]
@jcfr Sorry for the delay! I wouldn't mind transferring those repositories to Slicer organization. I would like to keep it for now (if possible) as there are a few features I'm using but not available in the Slicer core.

**Comment by jcfr** [comment]
@tokjun Thanks for the follow up :pray: 

Once you accept the invitation to join the Slicer organization, you should be able to submit transfer requests:

image

**Comment by tokjun** [comment]
@jcfr Thank you! I've just accepted the invitation and transferred the two extensions.

**Pull request merged**
